title: Java Interview Notes
description: Java · Spring/Spring Cloud · Databases · Computer Networks · OS · Redis · MQ · Distributed Systems

theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


markdown: kramdown